[tool.poetry]
name = "7407-DriveCode-2021-Python"
version = "0.1.0"
description = ""
authors = ["Ethan Chapman <ethan.chapman0@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8.6"
robotpy = {extras = ["commands2", "ctre", "rev"], version = "^2021.1.10"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
